apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: bubble-animation-app
  namespace: openshift-gitops
spec:
  destination:
    namespace: bubble-animation
    server: https://kubernetes.default.svc 
  project: default 
  source: 
    path: argocd-openshift-main/argocd-openshift-main/bubble-animation/application-mainfest
    repoURL: https://github.com/ajisha-sb/bubble-application
    targetRevision: main
  syncPolicy: 
    automated:
      prune: true
      selfHeal: false
    syncOptions:
    - CreateNamespace=true
